import Contador from "@/components/Contador";
import Helloworld from "@/components/Helloworld";
import Info from "@/components/Info";
import User from "@/components/User";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Meu Primeiro Site em React</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Olá Mundo! Meu Primeiro Site em React!</h1>
      {/* Comentário no JSX */}
      {/* Importando o primeiro componente */}
      <Helloworld />
      <User />
      <br />
      <Contador />
      <br />
      <Info />
    </>
  );
}
